### ISSUE TITLE
Suport for protocol 91

### ISSUE THREAD

**Issue by subdeseo** [brugal/wolfcamql#1]
Hi, 
I see that the demos from QuakeCon are all protocol 91 (*). Hopefully you can take a look at it.

The error I see (from Com_Error) is:
> ERROR: invalid playerState field count:  58 : 50

BTW, this is in wolfcamql11.0test9.

Cheers, and many thanks for WolfcamQL!

*) http://quakeconcdn.org/#/

**Comment by brugal** [comment]
Protocol 91 still isn't complete but those and other fatal errors should be fixed since
48df2d125713ae4f234acfbc8650f9b1a2ea28ff

**Comment by subdeseo** [comment]
Yes, I have noticed. Many thanks for your effort. Much appreciated.
