### ISSUE TITLE
RTCW wolfcam

### ISSUE THREAD

**Issue by jellegrammens** [brugal/wolfcamql#14]
Hello Brugal,

Sorry to put this here, but i couldn't find any other way to contact you on github. Do you still have a wolfcam version for RTCW that was made back for the 1.33 version? 

Kind regards,
Jelle

**Comment by brugal** [comment]
Hi Jelle,

I don't think it was ever built for 1.33.  I have wolfcam-rtcw-0_0_4.zip which is for 1.41?.  I also have wolfcam-rtcw-0.0.5-src.tar.gz if you want to try and port/build for 1.33.  Let me you know if you want these.  Send me an email at   basturdo@yahoo.com.

brugal
