### ISSUE TITLE
Every time the player takes damage, the screen turn completely grey for 0.5 s

### ISSUE THREAD

**Issue by oskarkv** [brugal/wolfcamql#2]
Every time the player takes damage, the screen turn completely grey for 0.5 s. It's like a wall of grey right before your eyes.

**Comment by brugal** [comment]
This should have been fixed in recent test build/releases.  Which version were you using?

**Comment by oskarkv** [comment]
I don't know exactly which it was; I reinstalled and it went away.

**Comment by brugal** [comment]
The last ql updates changed the name and location for blood related settings so it might have been the older pk3s installed in the wolfcamql folder.  Closing the issue.  Let me know if the problem pops up again.

**Comment by brugal** [comment]
Can you post cgameboot.log?  Ex:

    C:\Users\[username]\AppData\Roaming\Wolfcamql\wolfcam-ql\cgameboot.log

**Comment by brugal** [comment]
Also check these:

]\cvarsearch enemy
cg_whEnemyShader set to default ''
cg_whEnemyColor set to default '0xaf1f00'
cg_whEnemyAlpha set to default '30'
cg_enemyModel set to default 'keel/bright'
cg_enemyHeadModel set to default 'keel/bright'
cg_enemyHeadSkin set to default ''
cg_enemyTorsoSkin set to default ''
cg_enemyLegsSkin set to default ''
cg_enemyHeadColor set to default '0x2a8000'
cg_enemyTorsoColor set to default '0x2a8000'
cg_enemyLegsColor set to default '0x2a8000'
cg_enemyRailColor1 set to default ''
cg_enemyRailColor2 set to default ''
cg_enemyRailRings set to default '0'
cg_enemyRailNudge set to default '1'
cg_enemyRailItemColor set to default ''
cg_enemyFlagColor set to default '0x00ff00'
cg_cpmaUseNtfEnemyColors set to default '1'
cg_disallowEnemyModelForTeammates set to default '1'
cg_grenadeEnemyColor set to default '0x00ff00'
cg_grenadeEnemyColorAlpha set to default '255'
cg_dominationPointEnemyColor set to default ''
cg_dominationPointEnemyAlpha set to default ''
cg_drawDominationPointStatusEnemyColor set to default ''
]\cg_force
    cg_forceModel = "0"  default
    cg_forcePovModel = "0"  default
    cg_forcePovModelIgnoreFreecamTeamSettings = "0"  default

**Comment by fragtion** [comment]
Ah, the so model coloring commands and values are a bit different to QL. Got it working perfectly now with your guide above, thanks a lot! Someone needs to create a guide showing the relative 1:1 commands lol.. this info was not easy to find. Or even better, wolfcam could be improved to support QL configs more natively and do the command translations internally
