### ISSUE TITLE
About keeping vid_restarting

### ISSUE THREAD

**Issue by em92** [brugal/wolfcamql#22]
https://github.com/brugal/wolfcamql/blob/268c71f29918617c3c35fc3db7c38fd210ea79ae/FIXME#L2092

ioquake3 had the same problem. Somehow it was fixed in https://github.com/ioquake/ioq3/pull/310/commits/e0a367451f04988790384fc59d998b6dcb6bf2e3

**Comment by brugal** [comment]
Thank you.  That fixes it.  https://github.com/brugal/wolfcamql/commit/c8cfe5043883b85ec448f81615d6e5085d62c6ea
