### ISSUE TITLE
Hi Brugal!

### ISSUE THREAD

**Issue by Lotzyprod** [brugal/wolfcamql#24]
Can you add "cl_renderer 2" in the next update and update "ioquake" to this version http://edawn-mod.org/forum/viewtopic.php?f=6&t=7 ? specifically for:  "* Added experimental "screenMap" texture support for shader stages, can be used for real-time on-hand weapon reflections"

**Comment by Lotzyprod** [comment]
https://github.com/ec-/Quake3e/blob/master/code/renderer/tr_shade_calc.c#L984 - source code with reflections

**Comment by brugal** [comment]
Hi, I'll take a look.  Is there an example shader and/or video showing what the result should look like?

**Comment by brugal** [comment]
added here:  https://github.com/brugal/wolfcamql/commit/ececf4ff3d5d14375bcbc1eacde40188fd598db8
