### ISSUE TITLE
"/follow" doesn't show health/armor in MVD demos

### ISSUE THREAD

**Issue by KittenIgnition** [brugal/wolfcamql#25]
![shot0006](https://user-images.githubusercontent.com/37711815/38271365-4d038352-3754-11e8-8a79-e3f62426f063.jpg)

CPMA demos, obviously.

**Comment by brugal** [comment]
Should be fixed here (still missing weapon info):  

https://github.com/brugal/wolfcamql/commit/00b49ec77daa8da32c557f227fe8492644ba0cc1
