### ISSUE TITLE
animMap still limited to 8 frames with opengl2 renderer

### ISSUE THREAD

**Issue by Legless** [brugal/wolfcamql#29]
I really liked new stuff this renderer provides, but it is broken with large animmaps.

Any chance to fix this?

![image](https://user-images.githubusercontent.com/2097587/46583191-692a1380-ca5b-11e8-8570-e5ab2fc7e7d3.png)

**Comment by brugal** [comment]
thanks!  change added

**Comment by brugal** [comment]
https://github.com/brugal/wolfcamql/commit/0d2c50cb82a3eb4e24a2f7c7405d2df32044f14e
