### ISSUE TITLE
Restricted to x86 architexture.

### ISSUE THREAD

**Issue by Danfun64** [brugal/wolfcamql#3]
My computer is running x86_64 ubuntu. When I type in make, it forces this software to compile on 32-bit mode. While my computer can run this program, your forcing of 32-bit mode pretty much prevents this software from being compiled and run on arm computers. Why have you set it up like this?

**Comment by brugal** [comment]
You just have to fix one bug in the Makefile (remove hard coded -m32 in c++ flags) and you should be able to compile with 'make ARCH=x86_64'

diff --git a/Makefile b/Makefile
index b177606..bf8cea2 100644
--- a/Makefile
+++ b/Makefile
@@ -1045,7 +1045,7 @@ endef
 
 define DO_CPP
 $(echo_cmd) "CPP $<"
-$(Q)$(CPP) -Wall $(CFLAGS) $(CLIENT_CFLAGS) $(OPTIMIZE) -m32 -o $@ -c $<
+$(Q)$(CPP) -Wall $(CFLAGS) $(CLIENT_CFLAGS) $(OPTIMIZE) -o $@ -c $<
 endef
 
 define DO_SMP_CC

**Comment by brugal** [comment]
also, the default 32-bit default build is set in Makefile.local (ARCH=i386) just as a convenience

**Comment by Danfun64** [comment]
I don't think this is worth creating a whole new issue, but I don't know if pming people is possible in github. I tried compiling a new build with arch=x86_64. I can get the program to run, but I can't see anything. My baseq3 contains pak00.pk3, and I copied the .so, vm folder, and everything in package-files/wolfcam-ql to a wolfcam-ql directory. It cache's the textures, and then I can't see anything. Help?

**Comment by brugal** [comment]
missing some 64bit padding for render commands, try this version: https://github.com/brugal/wolfcamql/commit/eb5667b81923d28dab3b135b9a42040ec6aaa35f

**Comment by Danfun64** [comment]
Also, client libs for x86_64 should also contain -lX11

**Comment by brugal** [comment]
also added in the same commit
