### ISSUE TITLE
demoMsglen limit too low

### ISSUE THREAD

**Issue by ghost** [brugal/wolfcamql#33]
ERROR: CL_ReadDemoMessage: demoMsglen (930417934) > MAX_MSGLEN (32768)

This is a Defrag demo, over 70 minutes long, that won't open in any engine other than q3e. Pls increase limit!

**Comment by em92** [comment]
Example demo required to make sure that future fix will work.

**Comment by brugal** [comment]
Could you send the demo?  It might not be a message length limit.  It could be something else that causes an invalid value to be read for length.

**Comment by KittenIgnition** [comment]
https://www.dropbox.com/s/ahqjh8zp9yzno31/vq3-cj%5Bmdf.vq3%5D00.01.000%28HLIDSKJALF.France%29.dm_68?dl=0
________________________________
