### ISSUE TITLE
Picmip 

### ISSUE THREAD

**Issue by ianahl** [brugal/wolfcamql#35]
Sry, idk if there is any active forum for wolfcamql atm so i just ask here. 
Is there a way to get r_picmip 10 (just on map) without affecting the explosions, impacts, items etc?

**Comment by brugal** [comment]
Hello, there isn't a specific option for that but you can get that affect by editing shaders and adding 'nopicmip' directives.  If you are using Quake Live's media most of that is already set for the things you listed.  Ex:   scripts/gfx.shader

rocketExplosion
{
        nopicmip
        cull disable
        {
                animmap 8 ...
        }
        ...
}
