### ISSUE TITLE
wolfcamql no longer working on MacOS Catalina (64-bit)

### ISSUE THREAD

**Issue by mgaertne** [brugal/wolfcamql#37]
Recently, ioquake3 got a patch to work under MacOS Catalina, but unfortunately wolfcamql just ships with a 32-bit executable, that will no longer work with MacOS Catalina. I tried to manually compile it on updated macOS, but failed to get it working.

**Comment by brugal** [comment]
64-bit Mac builds enabled with:

https://github.com/brugal/wolfcamql/commit/2855d58ff781dfb70ed0cc1fbb06ca8b5d19d3cb

Can you try this version?

https://github.com/brugal/wolfcamql/releases/download/v12.3test3/wolfcamql-12.3test3.zip

**Comment by mgaertne** [comment]
After granting access to all the dynamic libraries, it seems to work. The only downside is a change in the color pallette on my desktop.

**Comment by brugal** [comment]
Try deleting your q3config.cfg file.  It might have reverted to 'safe' settings after the previous crashes.

ex:

/Users/acano/Library/Application Support/Wolfcamql/wolfcam-ql/q3config.cfg
