### ISSUE TITLE
Head and Model inconsistent with gameplay

### ISSUE THREAD

**Issue by Danfun64** [brugal/wolfcamql#4]
This is probably very silly, but hear me out.

In Quake Live, I have my model set to Doom/Blue. Obviously in team based matches where I am red the model automatically becomes Doom/Red. How do I set wolfcamql so that it consistently goes with whatever model I was using in the match? If that's not possible, than how do I get the headmodel so that it is not sarge? the model command works but the headmodel command is ignored.

**Comment by brugal** [comment]
That should be the default behavior unless you are using cg_forcePovModel 1.  That only changes the model and not the headmodel since it's mostly about watching first person view with your own sounds.

**Comment by Danfun64** [comment]
Is there a way to have both cg_forcepovmodel 1 and have the color match the team the player is in?

**Comment by brugal** [comment]
Try this https://github.com/brugal/wolfcamql/commit/d030a27c0f94491da27fb937dc968958d7fcf02a
You'll need to set 'model' to just 'doom' instead of 'doom/blue' so that the skin is picked automatically.

**Comment by Danfun64** [comment]
Unfortunately, I would have like to use a colored skin when playing ffa demos.

**Comment by brugal** [comment]
Should be fixed with this: https://github.com/brugal/wolfcamql/commit/3474100ce84219c558d91906608f88d4bf35b907

**Comment by Danfun64** [comment]
Should have commented a few days ago.

Yes, it is fixed. However, since you say that the solution was "hacky", not sure whether this issue should be closed until a proper fix is implemented...

**Comment by brugal** [comment]
I think it's probably correct the way it is now so I'll go ahead and close the issue.  The only thing missing is support for 'headmodel' but that's something else since support for that needs to be added for team and enemy models as well.
