### ISSUE TITLE
Build from source on Windows

### ISSUE THREAD

**Issue by Donaldduck8** [brugal/wolfcamql#40]
Could you please provide a rough guide of how to compile wolfcam from source on Windows?

**Comment by brugal** [comment]
I don't think I've ever built it from Windows.  I use the cross.sh script in Linux to create the Windows binaries.  You'd need mingw and make support so it might be possible with Cygwin:

    https://cygwin.com/install.html

**Comment by brugal** [comment]
This fixes a dependency issue for Cygwin:
https://github.com/brugal/wolfcamql/commit/004a744300527d8a34bc56fc5b26260cf68fa866

Tested with Cygwin 3.1.7 and 'make' and 'ARCH=x86 make' work correctly.
