### ISSUE TITLE
MVD Playback

### ISSUE THREAD

**Issue by Kr3m** [brugal/wolfcamql#47]
I load an MVD demo into wolfcamql and it won't let me switch players or do much of anything.  Is there no support for this?  Demo was recorded in the Q3Plus mod (older ExcessivePlus).

**Comment by brugal** [comment]
I'm not sure.  Would you be able to send or post a demo?

**Comment by Kr3m** [comment]
[demo.zip](https://github.com/brugal/wolfcamql/files/10951520/demo.zip)

Oddly it also displays the Harvester gametype which is gametype 7, and FTAG is gametype 8 in a lot of mods, though I realize there's no real standardization for gametype numbers.

**Comment by brugal** [comment]
There are a few things off like game type but you should be able to follow others using the /follow console command.  Ex:

/players
 X  00: wtfisarail
 X  01: {ReFleX}Kr3m
 X  02: SnortLaxatives    [demo taker]
(warmup) 0:16 CG_ParseScores() argc (43) != 4
(warmup) 0:21 CG_ParseScores() argc (43) != 4
]/follow 0

**Comment by Kr3m** [comment]
Oh cool.  Thanks man.  =D
