### ISSUE TITLE
Trojan Detected?

### ISSUE THREAD

**Issue by Phoenix-Films** [brugal/wolfcamql#49]
Assuming this must be a false-positive? Surely?

> The app D:\Quake\wolfcamql12.6test6\wolfcamql.exe infected with Gen:Variant.Barys.437950 was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by brugal** [comment]
Looks like a false positive.  I tested a new build and uploaded it to https://www.virustotal.com and got the same score from Bitdefender and others.  I disabled libcurl and the warnings went away.  Ex:

diff -r 2edc3330d210 Makefile.local
--- a/Makefile.local    Wed Jun 14 06:25:26 2023 -0400
+++ b/Makefile.local    Fri Jul 28 06:55:00 2023 -0400
@@ -1,5 +1,6 @@
 VERSION=12.6test8
 
+USE_CURL=0
 USE_CODEC_VORBIS=1
 USE_FREETYPE=1
 BUILD_MISSIONPACK=0
----

I guess the ability to download files automatically flags it with some anti-virus scanners.

**Comment by Phoenix-Films** [comment]
Hmm okay. I figured as much, but thanks for confirming. I've used wolfcam in the past w/o issues so was just surprised to see this and can never be too careful.
