### ISSUE TITLE
Lightning shader is broken.

### ISSUE THREAD

**Issue by Danfun64** [brugal/wolfcamql#5]
I'm not sure why, but (at least in one demo) I get the error RE_RegisterShader(lightningBolt1) failed. In the demo and another one, whenever somebody fired the lightning gun, what came out was a large untextured bar. Do you think a quake live update broke the shader in wolfcamql?

**Comment by brugal** [comment]
Can you post the demo?  Also, are you using the latest ql pak00.pk3?  That shader hasn't changed in a very long time.

**Comment by Danfun64** [comment]
Sorry for making you wait...

https://drive.google.com/file/d/0B8lbmaOG_ORKeTBmWnkwTkFRQWc/view?usp=sharing

**Comment by brugal** [comment]
Thank you.  It's the workshop item (pro-q3dm6.pk3).  It has a 'scripts/lightningnew.shader' file that replaces the one in quake live.  Looks like workshop items in ql aren't like regular mods and can't replace content.  I'll change the workshop loading order to match.

**Comment by brugal** [comment]
should be fixed here:  https://github.com/brugal/wolfcamql/commit/0df96210e9211c9c149d3f7cd1bea9b831c2222c
