### ISSUE TITLE
Heavy machinegun doesn't appear in the game

### ISSUE THREAD

**Issue by aibolith** [brugal/wolfcamql#50]
Hi. I found an issue where hmg doesn't appear on a map when it's loaded into WolfcamQL. If I start a QL server and load the map, the hmg is present. But not in WolfcamQL where ammo for hmg spawns but the weapon itself doesn't. Can I have any directions on how to fix it?

**Comment by brugal** [comment]
Looks like a bug.  Fixed here:
    https://github.com/brugal/wolfcamql/commit/25f4a1fe4b12f9f8fad9da0980cdc8f8e5383b5c

Can you try this version?
    https://github.com/brugal/wolfcamql/releases/tag/v12.6test9

**Comment by aibolith** [comment]
@brugal Tried it, hmg works now! Thank you for incredibly quick assistance! Also allow me to notice how cool it is that WolfCam's version of QL does have native 21:9 resolution and works perfectly on ultrawide monitors, while official QL still only has 16:9 in 2023.
