### ISSUE TITLE
Playback VOIP

### ISSUE THREAD

**Issue by Danfun64** [brugal/wolfcamql#6]
Quake Live servers have VOIP capability, but I can't hear it at all in Wolfcamql. Can this be fixed?

**Comment by brugal** [comment]
The voice data isn't recorded in the demo files so I'm afraid it can't be fixed.

**Comment by Danfun64** [comment]
Oh...

Well, I don't know what good this will do, but: https://steamcommunity.com/app/282440/discussions/0/351659808481352185/
